# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andy Nilipour
tagline:          
description:      
url:              http://anilipour.github.io
baseurl:          /

author:
  name:           'Andy Nilipour'
  url:            https://github.com/anilipour

paginate:         5

# Custom vars
version:          1.2

github:
  repo:           https://github.com/anilipour/

ads_link:         https://ui.adsabs.harvard.edu/search/q=%20author%3A%22nilipour%22%20year%3A2020-&sort=date%20desc%2C%20bibcode%20desc&p_=0

