# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andy Nilipour
tagline:          
description:      
url:              http://anilipour.github.io
baseurl:          /pages/

author:
  name:           'Andy Nilipour'
  url:            https://github.com/anilipour

paginate:         5

# Custom vars
version:          1.1

github:
  repo:           https://github.com/anilipour/
