# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Andy Nilipour
tagline:          
description:      
url:              http://anilipour.github.io
baseurl:          /

author:
  name:           'Andy Nilipour'
  url:            https://github.com/anilipour

paginate:         5

# Custom vars
version:          

github:
  repo:           
